(module
  (import "env" "call_log" (func $call_log (param i32)))
  (import "env" "buffer" (memory 1))
  (global $start_string (import "env" "start_string") i32)
  (global $string_len i32 (i32.const 12))
  (data (global.get $start_string) "hello world!")	
  (func (export "helloworld")
    (call $call_log (global.get $string_len))
  )
)